### ISSUE TITLE
Very Nice For V1. However...

### ISSUE THREAD

**Issue by TheRealJake12** [Goldie5fnf/Kade-Engine-Legacy#1]
Right Off The Bat, I Noticed Some Issues. 

Memory Info Isn't Accurate. Like. At All.

System Info Isn't Needed. This Is A Game. Not Malware.

UI Is Controlled With Arrows Only Pretty Much. People Use DFJK Or Other Keybinds To Navigate Menus.

Optimization Isn't Terrible But It's Not The Best.

Game HUD Overlaps Other Parts Of Itself.

Aside From That, Pretty Good So Far. Keep It Up.

**Comment by Goldie5fnf** [comment]
1. maybe you are about moments like 100 mb/400 mb, this is as i know max ram use on current state,it clears every stage
2. maybe? im gonna keep it anyway
3.yeah, must add it.
4. i didnt had any big frame drops,there was 0 fps in chart editor earlier but it is already fixed
5. Yeah... Botplay is under bg for arrows and icons is above of song info
